// data_atmosphere.js
const ATMOSPHERIC_EFFECTS = [
  "swirling particle vortices",
  "swirling spore curtains",
  "swirling auroral bands",
  "swirling plasma streamers",
  "swirling foam bubbles",
  "swirling gravity ripples",
  "swirling pressure fronts",
  "swirling ion storms",
  "swirling fog banks",
  "swirling light canals",
  "swirling sound mirages",
  "swirling chemiluminescent mists",
  "swirling mirror clouds",
  "swirling filamentary lightning",
  "swirling phase-sheen layers",
  "swirling entropy eddies",
  "swirling magnetic filaments",
  "swirling temporal waves",
  "swirling phonon clouds",
  "swirling charged dust devils",
  "towering particle vortices",
  "towering spore curtains",
  "towering auroral bands",
  "towering plasma streamers",
  "towering foam bubbles",
  "towering gravity ripples",
  "towering pressure fronts",
  "towering ion storms",
  "towering fog banks",
  "towering light canals",
  "towering sound mirages",
  "towering chemiluminescent mists",
  "towering mirror clouds",
  "towering filamentary lightning",
  "towering phase-sheen layers",
  "towering entropy eddies",
  "towering magnetic filaments",
  "towering temporal waves",
  "towering phonon clouds",
  "towering charged dust devils",
  "bioluminescent particle vortices",
  "bioluminescent spore curtains",
  "bioluminescent auroral bands",
  "bioluminescent plasma streamers",
  "bioluminescent foam bubbles",
  "bioluminescent gravity ripples",
  "bioluminescent pressure fronts",
  "bioluminescent ion storms",
  "bioluminescent fog banks",
  "bioluminescent light canals",
  "bioluminescent sound mirages",
  "bioluminescent chemiluminescent mists",
  "bioluminescent mirror clouds",
  "bioluminescent filamentary lightning",
  "bioluminescent phase-sheen layers",
  "bioluminescent entropy eddies",
  "bioluminescent magnetic filaments",
  "bioluminescent temporal waves",
  "bioluminescent phonon clouds",
  "bioluminescent charged dust devils",
  "charged particle vortices",
  "charged spore curtains",
  "charged auroral bands",
  "charged plasma streamers",
  "charged foam bubbles",
  "charged gravity ripples",
  "charged pressure fronts",
  "charged ion storms",
  "charged fog banks",
  "charged light canals",
  "charged sound mirages",
  "charged chemiluminescent mists",
  "charged mirror clouds",
  "charged filamentary lightning",
  "charged phase-sheen layers",
  "charged entropy eddies",
  "charged magnetic filaments",
  "charged temporal waves",
  "charged phonon clouds",
  "charged charged dust devils",
  "ionized particle vortices",
  "ionized spore curtains",
  "ionized auroral bands",
  "ionized plasma streamers",
  "ionized foam bubbles",
  "ionized gravity ripples",
  "ionized pressure fronts",
  "ionized ion storms",
  "ionized fog banks",
  "ionized light canals",
  "ionized sound mirages",
  "ionized chemiluminescent mists",
  "ionized mirror clouds",
  "ionized filamentary lightning",
  "ionized phase-sheen layers",
  "ionized entropy eddies",
  "ionized magnetic filaments",
  "ionized temporal waves",
  "ionized phonon clouds",
  "ionized charged dust devils",
  "cryogenic particle vortices",
  "cryogenic spore curtains",
  "cryogenic auroral bands",
  "cryogenic plasma streamers",
  "cryogenic foam bubbles",
  "cryogenic gravity ripples",
  "cryogenic pressure fronts",
  "cryogenic ion storms",
  "cryogenic fog banks",
  "cryogenic light canals",
  "cryogenic sound mirages",
  "cryogenic chemiluminescent mists",
  "cryogenic mirror clouds",
  "cryogenic filamentary lightning",
  "cryogenic phase-sheen layers",
  "cryogenic entropy eddies",
  "cryogenic magnetic filaments",
  "cryogenic temporal waves",
  "cryogenic phonon clouds",
  "cryogenic charged dust devils",
  "photic particle vortices",
  "photic spore curtains",
  "photic auroral bands",
  "photic plasma streamers",
  "photic foam bubbles",
  "photic gravity ripples",
  "photic pressure fronts",
  "photic ion storms",
  "photic fog banks",
  "photic light canals",
  "photic sound mirages",
  "photic chemiluminescent mists",
  "photic mirror clouds",
  "photic filamentary lightning",
  "photic phase-sheen layers",
  "photic entropy eddies",
  "photic magnetic filaments",
  "photic temporal waves",
  "photic phonon clouds",
  "photic charged dust devils",
  "magnetized particle vortices",
  "magnetized spore curtains",
  "magnetized auroral bands",
  "magnetized plasma streamers",
  "magnetized foam bubbles",
  "magnetized gravity ripples",
  "magnetized pressure fronts",
  "magnetized ion storms",
  "magnetized fog banks",
  "magnetized light canals",
  "magnetized sound mirages",
  "magnetized chemiluminescent mists",
  "magnetized mirror clouds",
  "magnetized filamentary lightning",
  "magnetized phase-sheen layers",
  "magnetized entropy eddies",
  "magnetized magnetic filaments",
  "magnetized temporal waves",
  "magnetized phonon clouds",
  "magnetized charged dust devils",
  "temporal particle vortices",
  "temporal spore curtains",
  "temporal auroral bands",
  "temporal plasma streamers",
  "temporal foam bubbles",
  "temporal gravity ripples",
  "temporal pressure fronts",
  "temporal ion storms",
  "temporal fog banks",
  "temporal light canals",
  "temporal sound mirages",
  "temporal chemiluminescent mists",
  "temporal mirror clouds",
  "temporal filamentary lightning",
  "temporal phase-sheen layers",
  "temporal entropy eddies",
  "temporal magnetic filaments",
  "temporal temporal waves",
  "temporal phonon clouds",
  "temporal charged dust devils",
  "fractured particle vortices",
  "fractured spore curtains",
  "fractured auroral bands",
  "fractured plasma streamers",
  "fractured foam bubbles",
  "fractured gravity ripples",
  "fractured pressure fronts",
  "fractured ion storms",
  "fractured fog banks",
  "fractured light canals",
  "fractured sound mirages",
  "fractured chemiluminescent mists",
  "fractured mirror clouds",
  "fractured filamentary lightning",
  "fractured phase-sheen layers",
  "fractured entropy eddies",
  "fractured magnetic filaments",
  "fractured temporal waves",
  "fractured phonon clouds",
  "fractured charged dust devils",
  "prismatic particle vortices",
  "prismatic spore curtains",
  "prismatic auroral bands",
  "prismatic plasma streamers",
  "prismatic foam bubbles",
  "prismatic gravity ripples",
  "prismatic pressure fronts",
  "prismatic ion storms",
  "prismatic fog banks",
  "prismatic light canals",
  "prismatic sound mirages",
  "prismatic chemiluminescent mists",
  "prismatic mirror clouds",
  "prismatic filamentary lightning",
  "prismatic phase-sheen layers",
  "prismatic entropy eddies",
  "prismatic magnetic filaments",
  "prismatic temporal waves",
  "prismatic phonon clouds",
  "prismatic charged dust devils",
  "acoustic particle vortices",
  "acoustic spore curtains",
  "acoustic auroral bands",
  "acoustic plasma streamers",
  "acoustic foam bubbles",
  "acoustic gravity ripples",
  "acoustic pressure fronts",
  "acoustic ion storms",
  "acoustic fog banks",
  "acoustic light canals",
  "acoustic sound mirages",
  "acoustic chemiluminescent mists",
  "acoustic mirror clouds",
  "acoustic filamentary lightning",
  "acoustic phase-sheen layers",
  "acoustic entropy eddies",
  "acoustic magnetic filaments",
  "acoustic temporal waves",
  "acoustic phonon clouds",
  "acoustic charged dust devils",
  "plasmatic particle vortices",
  "plasmatic spore curtains",
  "plasmatic auroral bands",
  "plasmatic plasma streamers",
  "plasmatic foam bubbles",
  "plasmatic gravity ripples",
  "plasmatic pressure fronts",
  "plasmatic ion storms",
  "plasmatic fog banks",
  "plasmatic light canals",
  "plasmatic sound mirages",
  "plasmatic chemiluminescent mists",
  "plasmatic mirror clouds",
  "plasmatic filamentary lightning",
  "plasmatic phase-sheen layers",
  "plasmatic entropy eddies",
  "plasmatic magnetic filaments",
  "plasmatic temporal waves",
  "plasmatic phonon clouds",
  "plasmatic charged dust devils",
  "spectral particle vortices",
  "spectral spore curtains",
  "spectral auroral bands",
  "spectral plasma streamers",
  "spectral foam bubbles",
  "spectral gravity ripples",
  "spectral pressure fronts",
  "spectral ion storms",
  "spectral fog banks",
  "spectral light canals",
  "spectral sound mirages",
  "spectral chemiluminescent mists",
  "spectral mirror clouds",
  "spectral filamentary lightning",
  "spectral phase-sheen layers",
  "spectral entropy eddies",
  "spectral magnetic filaments",
  "spectral temporal waves",
  "spectral phonon clouds",
  "spectral charged dust devils",
  "quantum particle vortices",
  "quantum spore curtains",
  "quantum auroral bands",
  "quantum plasma streamers",
  "quantum foam bubbles",
  "quantum gravity ripples",
  "quantum pressure fronts",
  "quantum ion storms",
  "quantum fog banks",
  "quantum light canals",
  "quantum sound mirages",
  "quantum chemiluminescent mists",
  "quantum mirror clouds",
  "quantum filamentary lightning",
  "quantum phase-sheen layers",
  "quantum entropy eddies",
  "quantum magnetic filaments",
  "quantum temporal waves",
  "quantum phonon clouds",
  "quantum charged dust devils",
  "radioactive particle vortices",
  "radioactive spore curtains",
  "radioactive auroral bands",
  "radioactive plasma streamers",
  "radioactive foam bubbles",
  "radioactive gravity ripples",
  "radioactive pressure fronts",
  "radioactive ion storms",
  "radioactive fog banks",
  "radioactive light canals",
  "radioactive sound mirages",
  "radioactive chemiluminescent mists",
  "radioactive mirror clouds",
  "radioactive filamentary lightning",
  "radioactive phase-sheen layers",
  "radioactive entropy eddies",
  "radioactive magnetic filaments",
  "radioactive temporal waves",
  "radioactive phonon clouds",
  "radioactive charged dust devils",
  "sublimating particle vortices",
  "sublimating spore curtains",
  "sublimating auroral bands",
  "sublimating plasma streamers",
  "sublimating foam bubbles",
  "sublimating gravity ripples",
  "sublimating pressure fronts",
  "sublimating ion storms",
  "sublimating fog banks",
  "sublimating light canals",
  "sublimating sound mirages",
  "sublimating chemiluminescent mists",
  "sublimating mirror clouds",
  "sublimating filamentary lightning",
  "sublimating phase-sheen layers",
  "sublimating entropy eddies",
  "sublimating magnetic filaments",
  "sublimating temporal waves",
  "sublimating phonon clouds",
  "sublimating charged dust devils",
  "supercooled particle vortices",
  "supercooled spore curtains",
  "supercooled auroral bands",
  "supercooled plasma streamers",
  "supercooled foam bubbles",
  "supercooled gravity ripples",
  "supercooled pressure fronts",
  "supercooled ion storms",
  "supercooled fog banks",
  "supercooled light canals",
  "supercooled sound mirages",
  "supercooled chemiluminescent mists",
  "supercooled mirror clouds",
  "supercooled filamentary lightning",
  "supercooled phase-sheen layers",
  "supercooled entropy eddies",
  "supercooled magnetic filaments",
  "supercooled temporal waves",
  "supercooled phonon clouds",
  "supercooled charged dust devils",
  "hyperdense particle vortices",
  "hyperdense spore curtains",
  "hyperdense auroral bands",
  "hyperdense plasma streamers",
  "hyperdense foam bubbles",
  "hyperdense gravity ripples",
  "hyperdense pressure fronts",
  "hyperdense ion storms",
  "hyperdense fog banks",
  "hyperdense light canals",
  "hyperdense sound mirages",
  "hyperdense chemiluminescent mists",
  "hyperdense mirror clouds",
  "hyperdense filamentary lightning",
  "hyperdense phase-sheen layers",
  "hyperdense entropy eddies",
  "hyperdense magnetic filaments",
  "hyperdense temporal waves",
  "hyperdense phonon clouds",
  "hyperdense charged dust devils",
  "rarefied particle vortices",
  "rarefied spore curtains",
  "rarefied auroral bands",
  "rarefied plasma streamers",
  "rarefied foam bubbles",
  "rarefied gravity ripples",
  "rarefied pressure fronts",
  "rarefied ion storms",
  "rarefied fog banks",
  "rarefied light canals",
  "rarefied sound mirages",
  "rarefied chemiluminescent mists",
  "rarefied mirror clouds",
  "rarefied filamentary lightning",
  "rarefied phase-sheen layers",
  "rarefied entropy eddies",
  "rarefied magnetic filaments",
  "rarefied temporal waves",
  "rarefied phonon clouds",
  "rarefied charged dust devils",
  "crystalline precipitation falling upward due to localized gravity anomalies",
  "sentient gas clouds that react to the creature's presence variant 1",
  "quantum foam bubbles spontaneously appearing and collapsing variant 2",
  "dimensional rifts leaking exotic matter into the atmosphere variant 3",
  "acoustic standing waves suspending particles in mid-air variant 4",
  "electromagnetic pulse bursts causing atmospheric ionization flashes variant 5",
  "phase-shifted matter flickering between solid and gaseous states variant 6",
  "thermal mirages that persist as physical membranes variant 7",
  "vortex rings that trap and circulate bioluminescent plankton variant 8",
  "shadow-sculpting winds that erase light from an area variant 9",
  "crystalline precipitation falling upward due to localized gravity anomalies variant 10",
  "sentient gas clouds that react to the creature's presence variant 11",
  "quantum foam bubbles spontaneously appearing and collapsing variant 12",
  "dimensional rifts leaking exotic matter into the atmosphere variant 13",
  "acoustic standing waves suspending particles in mid-air variant 14",
  "electromagnetic pulse bursts causing atmospheric ionization flashes variant 15",
  "phase-shifted matter flickering between solid and gaseous states variant 16",
  "thermal mirages that persist as physical membranes variant 17",
  "vortex rings that trap and circulate bioluminescent plankton variant 18",
  "shadow-sculpting winds that erase light from an area variant 19"
];